<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>


<div class="jm-info clearfix">
  <?php echo $this->getChildHtml() ?>
</div>
<div class="jm-legal">
	<?php echo $this->getCopyright() ?>
</div>
<script>
jQuery(document).ready(function(){
jQuery('.menu-region').each(function(obj){
	var height=jQuery(this).find('ul').height();
	if(height>20){
		jQuery(this).parents().find('.group').css('min-height',(height+50)+"px");	
		}
	});});
</script>