<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>


<div class="jm-info clearfix">
  <?php echo $this->getChildHtml() ?>
</div>
<div class="jm-legal">
	<?php echo $this->getCopyright() ?>
</div>
<script>
jQuery(document).ready(function(){
jQuery('.menu-region').each(function(obj){
	var height=jQuery(this).find('ul').height();
	if(height>20){
		jQuery(this).parents().find('.group').css('min-height',(height+50)+"px");	
		}
	});});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52565762-1', 'auto');
  ga('send', 'pageview');

</script>