<?php 
$categoryId=  $this->getData('category_id'); 
$_category = Mage::getModel('catalog/category')->load($categoryId);
$sub_cat=$_category->getChildrenCategories();

?>
<div class="menu-group">
<?php 
$html="";
foreach ($sub_cat as $cat)
{
	if($cat->getIsActive()){
	?>
<?php	
	if($cat->hasChildren())
	{
		foreach ($cat->getChildrenCategories() as $scat)
		{
			if($scat->getIsActive() && $scat->getProductCount())
				$html.="<li><a href='".$scat->getURL()."'>".$scat->getName()."</a></li>";
		}				
	}
	if($cat->getProductCount()||$html)
	{
		echo '<div class="menu-i"><div class="title">';
		echo "<h2><a href='".$cat->getURL()."'>".$cat->getName()."</a></h2></div>";
		if($html)
			echo "<ul>".$html."<ul>";
		echo "</div>";
	}
	$html='';
?>

<?php 	
}}
?>
</div>

<?php 
$layer =  Mage::getModel("catalog/layer");
$reset_cat=$layer->getCurrentCategory();
$layer->setCurrentCategory($_category);
$attributes = $layer->getFilterableAttributes();
foreach ($attributes as $attribute) {
	if ($attribute->getAttributeCode() == 'region') {
		
		$filterBlockName = 'catalog/layer_filter_attribute';
		//$result = $this->getLayout()->createBlock($filterBlockName)->setLayer($layer)->setAttributeModel($attribute)->init();
		
		$result=Mage::getModel($filterBlockName)->setAttributeModel($attribute)->setLayer($layer);
		$options=$attribute->getFrontend()->getSelectOptions();
		$optionsCount=Mage::getResourceModel($filterBlockName)->getCount($result);
		
		foreach ($options as $option) {
			if (is_array($option['value'])) {
				continue;
			}
			if (!empty($optionsCount[$option['value']])) {
				$data[] = array(
						'label' => $option['label'],
						'value' => $option['value'],
						
				);
			}

		}
		
		
		if(!empty($data))
		{
			//print_r($option);
			?>
			<div class="menu-region">
			<div class='title'><h2>Regions</h2></div>
			<ul class="">
			<?php 
			foreach($data as $option) {
			?>
			<li><a href="<?php echo $_category->getUrl()?>?region=<?php echo $option['value']?>"><span><?php echo $option['label']?></span></a></li>
			<?php
			}?>
			</ul>
			</div>
	<?php 
		}
	}
}
$layer->setCurrentCategory($reset_cat);
?>

