<?php

$layer = Mage::getSingleton('catalog/layer');
$cat_r=$layer->getCurrentCategory();
$rootCat=Mage::getModel('catalog/category')->load(Mage::app()->getStore()->getRootCategoryId());
$layer->setCurrentCategory($rootCat);

$block=$this->getLayout()->createBlock('joomlart_jmproductsslider/RegionL1list')->setTemplate("joomlart/jmproductsslider/horizontallist.phtml");

$attribute = Mage::getModel('eav/entity_attribute')->loadByCode(Mage_Catalog_Model_Product::ENTITY, 'region');
$region='';
foreach ( $attribute->getSource()->getAllOptions(true, true) as $option){

	$attributeArray[$option['value']] = $option['label'];
	if($option['label']==$cat_r->getName())
	{
		$region=$option['value'];
	}
}

$block->setTitle(" ")->setRegion($region);

$_subCaegories=explode(',',$rootCat->getChildren());
foreach ($_subCaegories as $scatid)
{
	$_subcat = Mage::getModel('catalog/category')->load($scatid);
	if(!($_subcat->getData("is_tile") || $_subcat->getName()=="Region"))
	{
		$block->setCategoryId($scatid);
		$count=count($block->getListProducts());
		if($count && (empty($catVal) || in_array($scatid,$catVal)))
		{
			$block->setTitle(" ")->setNumberItems(4)->setItemwidth(190)->setItemheight(272)->setWidth(165)->setHeight(150);
?>
<div class="list-type-slider">
<div class="block block-cate sp-block-cate">
<h1 class="catview"><a href='<?php echo $_subcat->getURL();?>?region=<?php echo $region;?>' ><?php echo $_subcat->getName()?></a></h1>
<a href='<?php echo $_subcat->getURL()?>'>(View all)</a>
<?php
		if($_subcat->hasChildren())
		{
			echo "<ul class='scatclass'>";
			foreach ($_subcat->getChildrenCategories() as $scat)
			{
				echo "<li><a href='".$scat->getURL()."?region=".$region."'>".$scat->getName()."</a></li>";
			}
			echo "</ul>";		
		}
?>

<p><?php echo $_subcat->getDescription()?></p>

</div>

<div><?php echo $block->toHtml(); ?></div>
</div>
<?php 
	
	}}}
	
	?>


<?php /*?>
<div class="list-type-slider">
<div class="block block-cate sp-block-cate">
<h1>Dining</h1>
<p>Adrianan Papell Women’s Long Sleeve lace dress adrinna papel women’s long sleeve lace dress drianna papel women’s long sleeve</p>
<ul>
<li><a href="#">View All</a></li>
</ul>
</div>
<div><?php echo $block->toHtml(); ?></div>
</div>
*/?>