<?php
$installer = $this;
$installer->startSetup();
$sql=<<<SQLTEXT
CREATE TABLE IF NOT EXISTS `country_currency` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(50) NOT NULL,
  `country_id` varchar(4) NOT NULL,
  `currency_id` varchar(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=248 ;

--
-- Dumping data for table `country_currency`
--

INSERT INTO `country_currency` (`id`, `country_name`, `country_id`, `currency_id`) VALUES
(1, 'Afghanistan', 'AF', 'USD'),
(2, 'Albania', 'AL', 'EUR'),
(4, 'Algeria', 'DZ', 'DZD'),
(5, 'American Samoa', 'AS', 'USD'),
(6, 'Andorra', 'AD', 'EUR'),
(7, 'Angola', 'AO', 'AOA'),
(8, 'Anguilla', 'AI', 'XCD'),
(9, 'Antigua and Barbuda', 'AG', 'XCD'),
(10, 'Argentina', 'AR', 'ARS'),
(11, 'Armenia', 'AM', 'AMD'),
(12, 'Aruba', 'AW', 'AWG'),
(13, 'Australia', 'AU', 'AUD'),
(14, 'Austria', 'AT', 'EUR'),
(15, 'Azerbaijan ', 'AZ', 'AZM'),
(16, 'Azores', 'PT', 'EUR'),
(17, 'Bahamas', 'BS', 'BSD'),
(18, 'Bahrain', 'BH', 'BHD'),
(19, 'Bangladesh', 'BD', 'BDT'),
(20, 'Barbados', 'BB', 'BBD'),
(21, 'Belarus', 'BY', 'BYR'),
(22, 'Belgium', 'BE', 'EUR'),
(23, 'Belize', 'BZ', 'BZD'),
(24, 'Benin', 'BJ', 'XOF'),
(25, 'Bermuda', 'BM', 'BMD'),
(26, 'Bhutan', 'BT', 'BTN'),
(27, 'Bolivia', 'BO', 'BOB'),
(28, 'Bonaire', 'AN', 'ANG'),
(29, 'Bosnia', 'BA', 'BAM'),
(30, 'Botswana', 'BW', 'BWP'),
(31, 'Brazil', 'BR', 'BRL'),
(32, 'British Virgin Islands', 'VG', 'USD'),
(33, 'Brunei', 'BN', 'BND'),
(34, 'Bulgaria', 'BG', 'EUR'),
(35, 'Burkina Faso', 'BF', 'XOF'),
(36, 'Burundi', 'BI', 'BIF'),
(37, 'Cambodia', 'KH', 'KHR'),
(38, 'Cameroon', 'CM', 'XAF'),
(39, 'Canada', 'CA', 'CAD'),
(40, 'Canary Islands', 'ES', 'EUR'),
(41, 'Cape Verde Island', 'CV', 'CVE'),
(42, 'Cayman Islands', 'KY', 'KYD'),
(43, 'Central African Republic', 'CF', 'XAF'),
(44, 'Chad', 'TD', 'XAF'),
(45, 'Chile', 'CL', 'CLP'),
(46, 'China, People’s Republic of ', 'CN', 'RMB'),
(47, 'Colombia', 'CO', 'COP'),
(48, 'Comoros', 'KM', 'USD'),
(49, 'Congo', 'CG', 'XAF'),
(50, 'Congo, The Democratic Republic of', 'CD', 'CDF'),
(51, 'Cook Islands', 'CK', 'NZD'),
(52, 'Costa Rica', 'CR', 'CRC'),
(53, 'Croatia', 'HR', 'EUR'),
(54, 'Curacao', 'AN', 'ANG'),
(55, 'Cyprus', 'CY', 'EUR'),
(56, 'Czech Republic', 'CZ', 'CZK'),
(57, 'Denmark', 'DK', 'DKK'),
(58, 'Djibouti', 'DJ', 'DJF'),
(59, 'Dominica', 'DM', 'XCD'),
(60, 'Dominican Republic', 'DO', 'DOP'),
(61, 'East Timor', 'TL', 'USD'),
(62, 'Ecuador', 'EC', 'USD'),
(63, 'Egypt', 'EG', 'EGP'),
(64, 'El Salvador', 'SV', 'USD'),
(65, 'England', 'GB', 'GBP'),
(66, 'Equatorial Guinea', 'GQ', 'XAF'),
(67, 'Eritrea', 'ER', 'ERN'),
(68, 'Estonia', 'EE', 'EEK'),
(69, 'Ethiopia', 'ET', 'ETB'),
(70, 'Europe', 'EP', 'EUR'),
(71, 'Faeroe Islands', 'FO', 'DKK'),
(72, 'Fiji', 'FJ', 'FJD'),
(73, 'Finland', 'FI', 'EUR'),
(74, 'France', 'FR', 'EUR'),
(75, 'French Guiana', 'GF', 'EUR'),
(76, 'French Polynesia', 'PF', 'XPF'),
(77, 'Gabon', 'GA', 'XAF'),
(78, 'Gambia', 'GM', 'GMD'),
(79, 'Georgia', 'GE', 'GEL'),
(80, 'Germany', 'DE', 'EUR'),
(81, 'Ghana', 'GH', 'GHC'),
(82, 'Gibraltar', 'GI', 'GIP'),
(83, 'Greece', 'GR', 'EUR'),
(84, 'Greenland', 'GL', 'DKK'),
(85, 'Grenada', 'GD', 'XCD'),
(86, 'Guadeloupe', 'GP', 'EUR'),
(87, 'Guam', 'GU', 'USD'),
(88, 'Guatemala', 'GT', 'GTQ'),
(89, 'Guernsey', 'GG', 'GBP'),
(90, 'Guinea', 'GN', 'GNF'),
(91, 'Guinea-Bissau', 'GW', 'XOF'),
(92, 'Guyana', 'GY', 'GYD'),
(93, 'Haiti', 'HT', 'HTG'),
(94, 'Holland', 'NL', 'EUR'),
(95, 'Honduras', 'HN', 'HNL'),
(96, 'Hong Kong', 'HK', 'HKD'),
(97, 'Hungary', 'HU', 'HUF'),
(98, 'Iceland', 'IS', 'ISK'),
(99, 'India', 'IN', 'INR'),
(100, 'Indonesia', 'ID', 'IDR'),
(101, 'Iraq', 'IQ', 'NID'),
(102, 'Ireland, Republic of', 'IE', 'EUR'),
(103, 'Israel', 'IL', 'ILS'),
(104, 'Italy', 'IT', 'EUR'),
(105, 'Ivory Coast', 'CI', 'XOF'),
(106, 'Jamaica', 'JM', 'JMD'),
(107, 'Japan', 'JP', 'JPY'),
(108, 'Jersey', 'JE', 'GBP'),
(109, 'Jordan', 'JO', 'JOD'),
(110, 'Kazakhstan', 'KZ', 'KZT'),
(111, 'Kenya', 'KE', 'KES'),
(112, 'Kiribati', 'KI', 'AUD'),
(113, 'Korea, South', 'KR', 'KRW'),
(114, 'Kosrae', 'FM', 'USD'),
(115, 'Kuwait', 'KW', 'KWD'),
(116, 'Kyrgyzstan', 'KG', 'KGS'),
(117, 'Laos', 'LA', 'LAK'),
(118, 'Latvia', 'LV', 'LVL'),
(119, 'Lebanon', 'LB', 'LBP'),
(120, 'Lesotho', 'LS', 'LSL'),
(121, 'Liberia ', 'LR', 'LRD'),
(122, 'Libya', 'LY', 'LYD'),
(123, 'Liechtenstein', 'LI', 'CHF'),
(124, 'Lithuania', 'LT', 'LTL'),
(125, 'Luxembourg', 'LU', 'EUR'),
(126, 'Macau', 'MO', 'MOP'),
(127, 'Macedonia (FYROM)', 'MK', 'EUR'),
(128, 'Madagascar', 'MG', 'MGA'),
(129, 'Madeira', 'PT', 'EUR'),
(130, 'Malawi', 'MW', 'MWK'),
(131, 'Malaysia', 'MY', 'MYR'),
(132, 'Maldives', 'MV', 'MVR'),
(133, 'Mali', 'ML', 'XOF'),
(134, 'Malta', 'MT', 'EUR'),
(135, 'Marshall Islands', 'MH', 'USD'),
(136, 'Martinique', 'MQ', 'EUR'),
(137, 'Mauritania', 'MR', 'MRO'),
(138, 'Mauritius', 'MU', 'MUR'),
(139, 'Mayotte', 'YT', 'EUR'),
(140, 'Mexico', 'MX', 'MXN'),
(141, 'Micronesia, Federated States of', 'FM', 'USD'),
(142, 'Moldova', 'MD', 'MDL'),
(143, 'Monaco', 'MC', 'EUR'),
(144, 'Mongolia', 'MN', 'MNT'),
(145, 'Montenegro', 'ME', 'EUR'),
(146, 'Montserrat', 'MS', 'XCD'),
(147, 'Morocco', 'MA', 'MAD'),
(148, 'Mozambique', 'MZ', 'MZM'),
(149, 'Namibia', 'NA', 'NAD'),
(150, 'Nepal', 'NP', 'NPR'),
(151, 'Netherlands', 'NL', 'EUR'),
(152, 'Netherlands Antilles', 'AN', 'ANG'),
(153, 'New Caledonia', 'NC', 'XPF'),
(154, 'New Zealand', 'NZ', 'NZD'),
(155, 'Nicaragua', 'NI', 'NIO'),
(156, 'Niger', 'NE', 'XOF'),
(157, 'Nigeria', 'NG', 'NGN'),
(158, 'Norfolk Island', 'NF', 'AUD'),
(159, 'Northern Ireland', 'GB', 'GBP'),
(160, 'Northern Mariana Islands', 'MP', 'USD'),
(161, 'Norway', 'NO', 'NOK'),
(162, 'Oman', 'OM', 'OMR'),
(163, 'Pakistan', 'PK', 'PKR'),
(164, 'Palau', 'PW', 'USD'),
(165, 'Panama', 'PA', 'PAB'),
(166, 'Papua New Guinea', 'PG', 'PGK'),
(167, 'Paraguay', 'PY', 'PYG'),
(168, 'Peru', 'PE', 'PEN'),
(169, 'Philippines', 'PH', 'PHP'),
(170, 'Poland', 'PL', 'PLN'),
(171, 'Ponape', 'FM', 'USD'),
(172, 'Portugal', 'PT', 'EUR'),
(173, 'Puerto Rico', 'PR', 'USD'),
(174, 'Qatar', 'QA', 'QAR'),
(175, 'Reunion', 'RE', 'EUR'),
(176, 'Romania', 'RO', 'ROL'),
(177, 'Rota', 'MP', 'USD'),
(178, 'Russia', 'RU', 'RUB'),
(179, 'Rwanda', 'RW', 'RWF'),
(180, 'Saba', 'AN', 'ANG'),
(181, 'Saipan', 'MP', 'USD'),
(182, 'Samoa', 'WS', 'WST'),
(183, 'San Marino', 'SM', 'EUR'),
(184, 'Saudi Arabia', 'SA', 'SAR'),
(185, 'Scotland', 'GB', 'GBP'),
(186, 'Senegal', 'SN', 'XOF'),
(187, 'Serbia', 'RS', 'EUR'),
(188, 'Seychelles', 'SC', 'SCR'),
(189, 'Sierra Leone', 'SL', 'SLL'),
(190, 'Singapore', 'SG', 'SGD'),
(191, 'Slovakia', 'SK', 'EUR'),
(192, 'Slovenia', 'SI', 'EUR'),
(193, 'Solomon Islands', 'SB', 'SBD'),
(194, 'South Africa', 'ZA', 'ZAR'),
(195, 'Spain', 'ES', 'EUR'),
(196, 'Sri Lanka', 'LK', 'LKR'),
(197, 'St. Barthelemy', 'GP', 'EUR'),
(198, 'St. Christopher', 'KN', 'XCD'),
(199, 'St. Croix', 'VI', 'USD'),
(200, 'St. Eustatius', 'AN', 'ANG'),
(201, 'St. John', 'VI', 'USD'),
(202, 'St. Kitts and Nevis', 'KN', 'XCD'),
(203, 'St. Lucia', 'LC', 'XCD'),
(204, 'St. Maarten', 'AN', 'ANG'),
(205, 'St. Martin', 'GP', 'EUR'),
(206, 'St. Thomas', 'VI', 'USD'),
(207, 'St. Vincent and the Grenadines', 'VC', 'XCD'),
(208, 'Suriname', 'SR', 'SRG'),
(209, 'Swaziland', 'SZ', 'SZL'),
(210, 'Sweden', 'SE', 'SEK'),
(211, 'Switzerland', 'CH', 'CHF'),
(212, 'Tahiti', 'PF', 'XPF'),
(213, 'Taiwan', 'TW', 'TWD'),
(214, 'Tajikistan', 'TJ', 'TJS'),
(215, 'Tanzania', 'TZ', 'TZS'),
(216, 'Thailand', 'TH', 'THB'),
(217, 'Tinian', 'MP', 'USD'),
(218, 'Togo', 'TG', 'XOF'),
(219, 'Tonga', 'TO', 'TOP'),
(220, 'Tortola', 'VG', 'USD'),
(221, 'Trinidad and Tobago', 'TT', 'TTD'),
(222, 'Truk', 'FM', 'USD'),
(223, 'Tunisia', 'TN', 'TND'),
(224, 'Turkey', 'TR', 'USD'),
(225, 'Turkmenistan', 'TM', 'TMM'),
(226, 'Turks and Caicos Islands', 'TC', 'USD'),
(227, 'Tuvalu', 'TV', 'AUD'),
(228, 'U.S. Virgin Islands', 'VI', 'USD'),
(229, 'Uganda', 'UG', 'UGX'),
(230, 'Ukraine', 'UA', 'UAH'),
(231, 'Union Island', 'VC', 'XCD'),
(232, 'United Arab Emirates', 'AE', 'AED'),
(233, 'United Kingdom', 'GB', 'GBP'),
(234, 'United States', 'US', 'USD'),
(235, 'Uruguay', 'UY', 'UYU'),
(236, 'Uzbekistan', 'UZ', 'UZS'),
(237, 'Vanuatu', 'VU', 'VUV'),
(238, 'Vatican City State', 'VA', 'EUR'),
(239, 'Venezuela', 'VE', 'VEB'),
(240, 'Vietnam', 'VN', 'VND'),
(241, 'Virgin Gorda', 'VG', 'USD'),
(242, 'Wales', 'GB', 'GBP'),
(243, 'Wallis and Futuna Islands', 'WF', 'XPF'),
(244, 'Yap', 'FM', 'USD'),
(245, 'Yemen', 'YE', 'YER'),
(246, 'Zambia', 'ZM', 'ZMK'),
(247, 'Zimbabwe', 'ZW', 'ZWD');

SQLTEXT;
$installer->run($sql);
$installer->endSetup();
	 