<?php 

$rulesCollection =  $this->getallcoupon();

?> 

<div class="block block-discount discount">
    <div class="block-title"><strong><span><?php echo $this->__('Coupons for You') ?></span></strong></div>
	<?php if(count($rulesCollection)>0): ?>
    <div class="block-content discount-form">
 
         <?php  
			foreach($rulesCollection as $voucher)
			{ if($voucher['voucher_status']==1)
				{
				?>
				<div>
		             <div><h3><?php echo $voucher['voucher_code']; ?></h3></div>
		             <div><?php echo  $voucher['description']; ?> </div>
		        </div>
				<?php  
				} 
			}
			
			?>
			 
    </div>
    <script type="text/javascript">decorateTable('allvouchers-table')</script>
    <?php else: ?>
    	<p><?php echo $this->__('Currenty No Coupon available.') ?></p>
	<?php endif ?>
    </div>
 
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
