<?php 
//echo "<pre>";
//$this->getAllvoucheratcart();
//print_r($this->getAllvoucheratcart());

//die;

$rulesCollection = $this->getAllvoucheratcart();// $this->getallcoupon();

?> 

<div class="block block-discount discount" style="overflow-y: auto; height: 240px">
    <div class="block-title"><strong><span><?php echo $this->__('Coupons for You') ?></span></strong></div>
	<?php if(count($rulesCollection)>0): ?>
    <div class="block-content discount-form" >
 
         <?php  
			foreach($rulesCollection as $voucher)
			{  
				$desc = substr($voucher['description'],0,500);
				?>
				<div style="border-bottom: 1px solid #ebebeb;">
		             <div><h3><?php echo $voucher['voucher_code']; ?></h3></div>
		             <div><?php echo  $voucher['offer_amount'].' Discount'; ?>
		              <?php if($desc){ ?>
		              	<span id="voucherdetailcall" style="cursor:pointer;float:right"  onclick="showdetail('<?php echo $voucher['voucher_code']; ?>');">Detail</span><?php }?>
		              </div>
		             <div id="voucherdescription<?php echo $voucher['voucher_code']; ?>" style="display:none;border: 1px solid #ebebeb;padding: 2px 5px;background: #fff" >
		             	<?php echo $desc; ?>
		             </div>
		        </div>
				<?php  
				 
			}
			
			?>
			 
    </div>
    <script type="text/javascript">decorateTable('allvouchers-table');</script>
    <?php else: ?>
    	<p style="padding: 20px;"><?php echo $this->__('No Coupon Available ') ?></p>
	<?php endif ?>
    </div>
 
<script type="text/javascript">
function showdetail(id)
{ 
	$('voucherdescription'+id).toggle();	 	
		
}

 
</script>
