<div class="page-title">
    <h1><?php echo $this->__('My Referals') ?></h1>
</div>
<?php 
$allreferal = $this->getAllreferal();
if(count($allreferal)>0): ?>
<table class="data-table" id="my-orders-table" >
    <thead>
        <tr>
            <th><?php echo  ('Friend Email') ?></th>
            <th><?php echo  ('Send Date') ?></th>
            <th><?php echo  ('Registration status') ?></th>
             
        </tr>
    </thead>
    <tbody>
    <?php foreach ($allreferal as $referal): ?>  	 		 	
        <tr>
            <td><?php echo $referal['receiver_emailid']; ?>&nbsp;</td>
            <td><?php echo date("D, j M, Y", strtotime($referal['senddate'])); ?>&nbsp;</td>
            <td><?php //echo $referal['register_status']==0?'Not Registered yet':'Registered'; 
						echo $referal['show_message']; ?>&nbsp;</td>
             
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders yet.') ?></p>
<?php endif ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
